baseURL: "https://mrafi.in/"
languageCode: "en-us"
title: "Mohammad Rafi"
theme: hugo-profile

Paginate: 3
disqusShortname: mrafi
googleAnalytics: "UA-36794379-1"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 2
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Mohammad Rafi"
  description: Software Engineer, Data Engineer, Full-stack Engineer
  favicon: "/favicon.ico"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # light

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor: 
  #   secondaryTextColor: 
  #   backgroundColor: 
  #   secondaryBackgroundColor: 
  #   primaryColor: 
  #   secondaryColor: 

  #   darkmode:
  #     textColor: 
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Rafi."
    subtitle: "I am a Seasoned Engineer, Software Architect and an Engineering manager."
    content: "Engineering Leader with 17+ years of experience, more recently in architecting large-scale data and AI-driven systems, with a strong foundation in machine learning, LLM personalization, and data platform engineering. Proven track record in leading high-impact cross-functional teams, managing end-to-end lifecycle of AI and data products, and aligning technical strategies with growth outcomes. Expertise includes building scalable data platforms, managing training pipelines for LLM fine-tuning and reinforcement learning, and delivering AI-powered features such as plagiarism detection and personalized experiences. Passionate about applying AI to solve real world problems and mentoring teams to push boundaries of innovation."
    image: /base.png
    work_image: /work_rafi.png
    education_image: /university_rafi.png
    button:
      enable: true
      name: "Resume (Linkedin)"
      url: "https://www.linkedin.com/in/linktorafi/"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/confessin
        - icon: fab fa-twitter
          url: https://twitter.com/rafi0101
      customIcons:
        - icon: /favicon.ico
          url: "https://mrafi.in"
  # About
  about:
    enable: true
    title: "More about me"
    image: '/fun_rafi.png'
    education_image: '/university_rafi.png'
    content: |-
      I am a software developer with a passion for data at scale. I have a background in computer science. I am currently working as an Enginnering Manager at [QuillBot](https://quillbot.com) in India. 
      
      I like to tinker with electronics, a fan of MCPs and constantly work on crappy ideas during my free time. I am a Father of 2 and a typical family man.
    skills:
      enable: true
      title: "Here are my favourite tech stacks"
      items:
        - "Python"
        - "Java"
        - "Big data stacks on distributed computing"
        - "Big Data warehouses like Snowflake, Redshift, Bigquery, Cassandra"
        - "AI specific toolsets like Langgraph, LangChain, n8n, Weaviate etc"
    Domains:
      enable: false
      title: "asdad"
      items:
        - "Python"
        - "Java"
        - ""

  # Experience
  experience:
    enable: true
    items:
      - job: " Engineering manager - Data Engineering and Growth"
        company: "QuillBot"
        companyUrl: "https://quillbot.com/"
        date: "Jun 2022 - May 2025"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://quillbot.com/plagiarism-checker"
        content: |
          Lead a high performing team comprising of Data Engineers, AI Engineers and BI developers
        
            - Managed AI platform for creating and training datasets, quality review process etc. Enabling LLM finetuning, classifications, reinforcement learning, RLHF etc.
            - Developed a data platform for 50M MAU from the ground up and created features and products for personalization and core LLM model improvements.
            - Streamlined Data Platform architecture with Snoplow, Iceberg, Kafka, DataFlow, Bigquery and Bigtable among others
            - Established a data engineering roadmap, driving strategic growth and technical excellence
            - Created a top-ranked plagiarism engine, achieving 3rd place in industry benchmarks.
            - Lead cross-functional projects aligning data engineering with growth goals, mentoring team members.
            - Transitioned into Growth focused Engineering management.
      
      - job: "Principal Architect / Manager: Data Analytics, Data Science"
        company: "Pitney Bowes"
        companyUrl: "https://pb.com"
        date: "Apr 2017 - Jun 2022 "
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://pb.com"
        content: |
          Managing Data Analytics / Data Science team for Sendtech vertical of PB. Building high performance teams, creating DS models to help Business and improving products
        
            - Leading Data Analytics / Data Science team for Sendtech business
            - Build and manage Reporting solutions, Business Intelligence Dashboards and Data science products
            - Developed an AdTech platform based on Location Intelligence (PB) and Location Trace data
      
      - job: "Principal Engineer"
        company: "niki"
        companyUrl: "https://niki.ai"
        date: "July 2016 - Mar 2017"
        info:
          enable: false
          # content: asd
        content: |
          Managing and mentoring team of Engineers Building a chat bot which works as a concierge for doing transactions for Indian markets.
            
            - Filed a patent on "Dialogue manager using Dynamic State machines". This is the central engine for the chatbot at Niki.
            - Developed a generic Natural language generator to support multiple languages and dialects.
      
      - job: "Senior Software Engineer"
        company: "InMobi"
        companyUrl: "https://inmobi.com"
        date: "May 2013- July 2016"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Worked in multiple teams, worked closely with product
            - Geo Enrichment Service, App Metadata and Performance business
            - Geo used to serve over 2 Billion request per day
            - Worked in technology diverse tech stack which includes Hadoop, Pig, Hive, R, Python, Java and JavaScript.
            - Under Geo: Built a framework for Ingesting all third party data.
            - Developed learning Models with Enriched (Geo, Places, POIs etc) AdServe Data to achieve better performance.
            - Under Performance I was responsible for UAC (Universal App catalogue) and LTV based prediction and service associated with it.
            - Under Data we built a BSSID Geocoder for Infering locations based on Wifi SSID, a lot of reporting and feedbacks were incorporated.

      - job: "Senior Software Engineer"
        company: "Google"
        companyUrl: "https://google.com"
        date: "July 2011- January 2013"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Worked as a Senior Software engineer - Full Stack
            - Worked on a Project management tool which was used by Google’s internal teams like Maps and Street view to streamline their processes.
            - Achieved readability in Python, to do code reviews for Python across Google

      - job: "Senior Open Source Developer"
        company: "HT Media"
        companyUrl: "https://www.htmedia.in/"
        date: "December 2010- July 2011"
        content:  |
          Worked as a Senior Software engineer - Full Stack
            - Worked as Search expert on Shine.com, a job portal.
            - Also worked on htcampus.com on a module which lets students apply for colleges directly through htcampus.
            - Rebuild and Inhoused Shine.com within 9 months. It was a celebrated achievement throughout the company

      - job: "Senior Software Engineer"
        company: "Position2"
        companyUrl: "https://www.position2.com/"
        date: "June 2008- December 2010"
        content:  |
          Worked as a full stack engineer
            - AutoBidding Platform for PPC which basically used historical keyword level data to predict bids for Platforms like Google Adwords, MSN and Yahoo.
            - Keyword Generation Tool (SEO) For creating a lot of related keywords based on the base set for optimization purposes, It created something like WordNet.
            - Brand Monitor, A Tool for monitoring online social media/ mainstream media presence. This tool was later sold to ThisMoment Inc.
  
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Technology"
        school:
          name: "ICFAI Tech, Hyderabad"
          url: "https://www.ifheindia.org/icfaitech/"
        date: "2004 - 2008"
        GPA: "7.4 out of 10"
        content: |-          
          B Tech
      
  # Achievements
  achievements:
    enable: true
    items:  
      - title: Python Readablity at Google
        content: Readability is an internal certification that shows you understand Google’s coding style and best practices for a specific language. Every CL must be written or reviewed by an engineer with readability in that language
        url: https://news.ycombinator.com/item?id=22620455
      - title: Winner of Best product and best team at Inmobi
        content: Winner of Best product and best team at Inmobi

  # projects
  projects:
    enable: true
    items:
      - title: Wedding website
        content: My Wedding website using scrollorama
        image: /wedding_ss.png
        featured:
          name: Link
          link: /wedding.html
        badges:
          - "HTML"
          - "Javascript"
      - title: VitaVim
        content: VitaVim. Your Essential daily intake for Vim.
        image: /vitavim.webp
        featured:
          name: Link
          link: https://github.com/confessin/vitavim
        badges:
          - "HTML"
          - "Javascript"
      - title: Social Media AI agent
        content: An AI agent which tunes your Insta reels and YT shorts algorithm to only show based on your preferences. Combat Doomscrolling.
        image: /Instagram-Logo.wine.png
        featured:
          name: Link
          link: https://www.linkedin.com/posts/linktorafi_ai-browserextensions-reinforcementlearning-activity-7344815870277292032-toOs
        badges:
          - "ChatGPT"
          - "MiniGPT-4"
          - "Social Media"

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: mrafi@mrafi.in
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/confessin
      linkedin: https://www.linkedin.com/in/linktorafi/
      twitter: https://twitter.com/rafi0101
      